# SPDX-license-identifier: CC0-1.0

[workspace]
name = "nsis-largestring-advancedlogging"
version = "3.11.0"
channels = ["conda-forge"]
platforms = ["win-64"]
preview = ["pixi-build"]

[package]
name = "nsis"
version = "3.11"
homepage = "https://nsis.sourceforge.io/Main_Page"
repository = "https://github.com/NSIS-dev/nsis"
description = "NSIS with advanced loggin and large strings enabled"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }